In [2]:
def occ(n,arr):
    mc=0
    freq=0
    for i in range(0,n):
        count=0
        for j in range(0,n):
            if (arr[i]==arr[j]):
                count+=1
        if (count>mc):
            mc=count
            freq=arr[i]
            
    return freq  
    
n=int(input())
arr=(input())
print(occ(n,arr))

5
0 2 0 6 9
0


In [6]:
n=(input())
a=[int,input().split()]
st=a[0]
lt=a[0]
l=len(a)
for i in range(l):
    if a[i]<st:
        st=a[i]
    elif a[i]>lt:
        lt=a[i]
print('{}\n{}'.format(st,lt))        


4
-2 0 8 4


TypeError: '<' not supported between instances of 'type' and 'type'

In [8]:
n=4
a = [-2, 0 ,8, 4]
st = a[0]
lt = a[0]
l = len(a)
if n<100:
    for i in range(l):
        if a[i] < st:
            st = a[i]
        elif a[i] > lt:
            lt = a [i]
print('{}\n{}'.format(st,lt)) 

-2
8


In [19]:
n=int(input())
a =list(map(int, input().split()))
st = a[0]
lt = a[0]
l = len(a)
if n<100:
    for i in range(l):
        if a[i] < st:
            st = a[i]
        elif a[i] > lt:
            lt = a [i]
print('{}\n{}'.format(st,lt)) 

-2
8


In [9]:
def uni(n,st):
    c=0
    for i in st:
        c+=1
        print(i,' - ',c)
        

In [28]:
def uni(n,st):
    
    for i in (st):
        c=st.count(i)
        print(i,' - ',c)

In [29]:
uni(4,'aman'
   )

m  -  1
n  -  1
a  -  2


In [31]:
n=3
arr1=input()
arr2=input()
arr1=set(arr1)
arr2=set(arr2)
if (arr1 & arr2 ):
    print(arr1 & arr2)

4 5 7
9 2 5
{' ', '5'}


In [34]:
n=int(input())
arr1=list(map(int, input().split()))
arr2=list(map(int, input().split()))
x=set(arr1).intersection(arr2)
print(x)

3
4 5 7
9 2 5
{5}


In [18]:
n=int(input())
arr1=list(map(int, input().split()))
arr2=list(map(int, input().split()))
if n>=1 and n<=1000:
    for i in arr1:
        if i in arr2:
            print(i)

3
4 5 7
9 2 5
5


In [37]:
n=int(input())
arr1=list(map(int, input().split()))
arr2=list(map(int, input().split()))
c = [value for value in arr1 if value in arr2]
c

3
4 5 7
9 2 5


TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [30]:
import numpy as np
n=3
arr1=np.array(input())
arr2=np.array(input())
inter=np.intersect1d(arr1,arr2)
print(inter)

4 5 7
9 2 5
[]


In [38]:
n=int(input())
x=str(420)
x=x.strip()
if n<1000000 and x in str(n):
    print('Caught')
else:
    print('Escaped')

97420
Caught


In [40]:



def printArr(arr, n):

	for i in range(n):
		print(arr[i], end = ' ')


def sortWithRemainder(arr, n, k):


	v = [[] for i in range(k)]


	for i in range(n):
		v[arr[i] % k].append(arr[i])
		

	for i in range(k):
		v[i].sort()

	j = 0
	
	for i in range(k):


		for it in v[i]:
			arr[j] = it
			j += 1

	printArr(arr, n)


if __name__=='__main__':

	arr = [ 12, 18 ,17 ,65, 46 ]
	n = len(arr)
	k = 4

	sortWithRemainder(arr, n, k)




12 17 65 18 46 

In [ ]:
5
A
ABA
ABA
A
A

In [33]:
n=5
if n>=1 and n<=100:
    for i in range(n):
        X=input()
        m=m.append(X)
co1=X.count('A')
co2=X.count('B')
if co1>co2:
    print('Co1 ',co1)
else:
    print('Co2 ',co2)

A


AttributeError: 'int' object has no attribute 'append'

In [46]:
n=int(input())
st=set(input())
st=str(st)
if n >=1 and n<=100:
    for i in (st):
        c=st.count(i)
        print(i,'-',c)

4
aman
{ - 1
' - 6
m - 1
' - 6
, - 2
  - 2
' - 6
n - 1
' - 6
, - 2
  - 2
' - 6
a - 1
' - 6
} - 1


In [49]:
n=int(input())
st=set(input())

st

4
aman


AttributeError: 'set' object has no attribute 'values'

In [ ]:
from collections import Counter
 
def prCharWithFreq(string):
 
    # Store all characters and their
    # frequencies using Counter function
    d = Counter(string)
 
    # Print characters and their frequencies in
    # same order of their appearance
    for i in d:
        print(i+'-'+str(d[i]), end=" ")
 
 
string = "aman"
prCharWithFreq(string)

In [ ]:
n=int(input())
st=set(input())
st=list(st)
if n >=1 and n<=100:
    for i in (st):
        c=st.count(i)
        print(i,'-',c)


In [54]:
from collections import Counter
n=int(input())
st=Counter(input())
for i in st:
    print(i+'-'+str(st[i]), end="\n")



4
aman
a-2
m-1
n-1


In [5]:
first=list(map(int, input().split()))
sec=list(map(int, input().split()))
marks1=sum(first)
marks2=sum(sec)
if marks1< marks2 and marks1<3600 and marks2<3600:
    print("First")
elif marks1==marks2  and marks1<3600 and marks2<3600:
    if first[-1]>sec[-1]:
        print('First')
    elif first[-1]<sec[-1]: 
        print('Second')
    elif first[-1]==sec[-1]:
        if first[0]>sec[0]:
            print('First')
        else:  
            print('second')
else:
    print("Second")          

120 90 70
90 80 110
Second


In [6]:
s='masai'
if len(set(s))==len(s) and len(s)<1000:
    print('Unique')
else:
    print('No')

No


In [ ]:
from collections import Counter   
a=0 2 0 6 9
lis=str(a) 
count=Counter(lis) 
print(count["4"])

In [14]:
def mostFrequent(arr, n):
    maxcount = 0;
    element_having_max_freq = 0;
    for i in range(0, n):
        count = 0
        for j in range(0, n):
            if(arr[i] == arr[j]):
                count += 1
        if(count > maxcount):
            maxcount = count
    element_having_max_freq = arr[i]
   
  return element_having_max_freq;
 

arr = [40,50,30,40,50,30,30]
n = len(arr)
print(mostFrequent(arr, n))

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 13)

In [16]:
n =int(input())
arr = list(map(int, input().split()))
maxcount = 0
element_having_max_freq = 0
for i in range(0, n):
    count = 0
    for j in range(0, n):
        if(arr[i] == arr[j]):
            count += 1
    if(count > maxcount):
        maxcount = count
        element_having_max_freq = arr[i]
print(element_having_max_freq)

5
0 2 0 6 9
0


In [26]:
n,k= map(int,input().split())
a=list(map(int,input().split()))
for i in a:
    m=i%k
    print(m,end=' ')

5 6
12 18 17 65 46
0 0 5 5 4 

In [30]:
n=
k=int(input())
arr=list(map(int,input().split()))
p = 0
v1 = []
v2 = []
 
for i in range(0, n, 1):
    if (arr[i] % k == p):
        v1.append(i)
        v2.append(arr[i])
v2.sort(reverse = False)
for i in range(0, len(v1), 1):
    arr[v1[i]] = v2[i]
for i in range(0, n, 1):
    print(arr[i], end = " ")

    

5
6
12 18 17 65 46
12 18 17 65 46 

In [4]:
s1=input()
s2=input()
n1=len(s1)
n2=len(s2)
if n1<1000 and n2<1000:
    if (n1!=n2):
        print('No')
    a=sorted(s1)
    s1=' '.join(a)
    b=sorted(s2)
    s2=' '.join(b)
    for i in range(0,n1,1):
        if(s1[i]!=s2[i]):
            print('No')
    else:
        print('Yes')

amit
mtia
Yes


In [13]:
s1=input()
s2=input()
n1=len(s1)
n2=len(s2)
a=sorted(s1)
s1=' '.join(a)
b=sorted(s2)
s2=' '.join(b)
if n1<1000 and n2<1000:
    if (n1!=n2):
        print('No')
    for i in range(0,n1,1):
        if(s1[i]!=s2[i]):
            print('No')
    else:
        print('Yes')   

amit
mtia
Yes


In [14]:
s1=input()
s2=input()
n1=len(s1)
n2=len(s2)

if n1<1000 and n2<1000:
    a=sorted(s1)
    s1=' '.join(a)
    b=sorted(s2)
    s2=' '.join(b)
    if (n1!=n2):
        print('No')
    for i in range(0,n1,1):
        if(s1[i]!=s2[i]):
            print('No')
    else:
        print('Yes')  

amit
mtia
Yes


In [15]:
import numpy as np


In [18]:
n,m,p=map(int,input().split())
n,m,p =map(np.array(int,input().split()))

4 3 2
1 2


TypeError: Field elements must be 2- or 3-tuples, got ''1''

In [20]:
n,m,p=map(int,input().split())
for i in range(n):
    for j in range(p):
        input().split()

4 3 2
1 2
1 2
1 2
1 2
1 2
1 2
1 2
1 2


In [22]:
import numpy as np
nmp= map(int,input().split())
n=np.array([input().split() for i in range(nmp[0])],int)
m=np.array([input().split() for i in range(nmp[1])],int)
print(np.concatenate((n,m),axis=0))

432


TypeError: 'map' object is not subscriptable

In [26]:
import numpy

NMP = list(map(int, input().split()))
N = numpy.array([input().split() for i in range(NMP[0])], int)
M = numpy.array([input().split() for i in range(NMP[1])], int)

print(numpy.concatenate((N, M), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [27]:
arr= list(map(int, input().split()))
print(np.reshape(arr,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
a=list(map(int,input().split()))
b=list(map(int,input().split()))
print(np.array(np.inner(a,b)))
print(np.array(np.outer(a,b)))

0 1
2 3
3
[[0 0]
 [2 3]]


In [32]:
n=int(input())
a=np.array([input().split() for i in range(n)],int)
b=np.array([input().split() for i in range(n)],int)
print(np.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [ ]:
import numpy as np
nm=list(map(int,input().split()))
n=np.array([input().split() for i in range(nm[0])],int)

print(np.max(np.min(n,axis=1)))


In [ ]:
nm=list(map(int,input().split()))
n=np.array([input().split() for i in range(nm[0])],int)
print(np.transpose(n))
print(n.flatten())

In [ ]:
np.set_printoptions(legacy='1.13')
a=list(map(float,input().split()))
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

In [ ]:
import numpy as np
np.set_printoptions(legacy='1.13')
nm=list(map(int,input().split()))
n=np.array([input().split() for i in range(nm[0])],int)
print(np.mean(n, axis = 1))
print(np.var(n, axis = 0))
print(np.std(n, axis= None))

In [35]:
import numpy as np
n,m=map(int,input().split())
a=np.array([input().split() for _ in range(n)],dtype=np.float)
print(np.mean(a,axis=1))
print(np.var(a,axis=0))
print(np.std(a,axis=None))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_11992/1220428697.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.array([input().split() for _ in range(n)],dtype=np.float)


In [37]:

N = int(input())
A = numpy.array([map(float, input().split()) for i in range(N)])
print(numpy.linalg.det(A))

2
1.1 1.1
1.1 1.1


LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [38]:
n = int(input().strip())
array = []
for _ in range(n):
    array.append([float(x) for x in input().strip().split(' ')])
print(numpy.linalg.det(array))

2
1.1 1.1
1.1 1.1
0.0
